# Generated by Django 4.0.4 on 2022-06-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='slug',
        ),
    ]
