# Generated by Django 4.0.4 on 2022-06-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_donation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='donation',
            name='slug',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
    ]
