# Generated by Django 4.0.4 on 2022-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_slug_donation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1234),
            preserve_default=False,
        ),
    ]
