# Generated by Django 4.0.4 on 2022-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='vidio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
