# Generated by Django 4.0.4 on 2022-06-04 09:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_news_vidio_news_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=123),
            preserve_default=False,
        ),
    ]
