# Generated by Django 4.0.4 on 2022-07-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
