# Generated by Django 4.0.4 on 2022-07-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_delete_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
