# Generated by Django 4.0.4 on 2022-07-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('-created_at',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
